#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#

"""Deploy resolved Conan binaries as immutable packages understood by O3DE.

Every host-context node in the Conan graph becomes its own archive. Dependencies are
never merged: generated Find modules download and resolve the packages they depend on.

The filename suffix is a deployment revision. Like Conan's package revision (PREV), it
is derived from the binary identity and contents rather than maintained by hand. It also
includes the generated O3DE files and this deployer, which are outside Conan's package
folder and therefore outside PREV.
"""

import hashlib
import json
import lzma
import os
import shutil
import stat
import tarfile

_HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(_HERE))

ARCHIVE_EXT = ".tar.xz"
HASH_EXT = ".tar.xz.SHA256SUMS"
CONTENT_HASH_EXT = ".tar.xz.content.SHA256SUMS"
MANIFEST_NAME = "SHA256SUMS"
DESCRIPTOR_NAME = "PackageInfo.json"

EXCLUDED_FROM_PAYLOAD = ("conaninfo.txt", "conanmanifest.txt")
_BUFFER = 1024 * 1024 * 10


# --------------------------------------------------------------------------------------
# hashing and archiving
# --------------------------------------------------------------------------------------

def _hash_file(path):
    hasher = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(_BUFFER), b""):
            hasher.update(chunk)
    return hasher.hexdigest()


def _package_reference(node):
    """Return Conan's complete, timestamp-free RREV:package-id#PREV identity."""
    pref = node.pref
    return pref.repr_notime() if hasattr(pref, "repr_notime") else repr(pref)


def _payload_files(folder):
    """Return every staged file, materialising directory symlinks without looping."""
    found = []

    def walk(directory, ancestors):
        for entry in sorted(os.scandir(directory), key=lambda item: item.name):
            if entry.is_dir():
                resolved = os.path.realpath(entry.path)
                if resolved in ancestors:
                    continue
                walk(entry.path, ancestors | {resolved})
            elif entry.is_file():
                found.append(os.path.relpath(entry.path, folder).replace(os.sep, "/"))

    walk(folder, {os.path.realpath(folder)})
    return sorted(found)


def _deployment_revision(node, stage, descriptor):
    """Content address for the complete O3DE image before its self-naming descriptor."""
    hasher = hashlib.sha256()
    hasher.update(b"o3de-engine-package-v2\0")
    hasher.update(_package_reference(node).encode("utf8"))
    hasher.update(b"\0")
    hasher.update(_hash_file(__file__).encode("ascii"))
    hasher.update(b"\0")
    hasher.update(json.dumps(descriptor, sort_keys=True, separators=(",", ":")).encode("utf8"))

    for relpath in _payload_files(stage):
        path = os.path.join(stage, relpath)
        info = os.lstat(path)
        hasher.update(b"\0" + relpath.encode("utf8") + b"\0")
        hasher.update(str(stat.S_IMODE(info.st_mode)).encode("ascii") + b"\0")
        if os.path.islink(path):
            hasher.update(b"link\0" + os.readlink(path).encode("utf8") + b"\0")
        hasher.update(_hash_file(path).encode("ascii"))
    return hasher.hexdigest()


def _writable(tarinfo):
    tarinfo.mode |= stat.S_IWUSR | stat.S_IWGRP | stat.S_IWOTH
    tarinfo.mtime = 0
    tarinfo.uid = tarinfo.gid = 0
    tarinfo.uname = tarinfo.gname = ""
    return tarinfo


def _archive(stage, relpaths, manifest_text, destination):
    with tarfile.open(destination, mode="w:xz", bufsize=_BUFFER,
                      preset=lzma.PRESET_EXTREME | 9) as tar:
        for relpath in relpaths:
            tar.add(os.path.join(stage, relpath), arcname=relpath, filter=_writable)

        manifest_path = os.path.join(stage, MANIFEST_NAME)
        with open(manifest_path, "wb") as handle:
            handle.write(manifest_text.encode("utf8"))
        tar.add(manifest_path, arcname=MANIFEST_NAME, filter=_writable)
        os.remove(manifest_path)


# --------------------------------------------------------------------------------------
# CMake generation
# --------------------------------------------------------------------------------------

_HEADER = """#
# Generated by extensions/deployers/engine_package.py. Do not edit.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
"""

_LIB_PATTERNS = {
    "Windows": ("{name}.lib", "lib{name}.lib", "{name}.dll.lib"),
    "Macos": ("lib{name}.a", "lib{name}.dylib", "{name}.a", "{name}.dylib"),
    "iOS": ("lib{name}.a", "lib{name}.dylib"),
    "_default": ("lib{name}.a", "lib{name}.so", "{name}.a", "{name}.so"),
}


def _unique(items):
    seen, result = set(), []
    for item in items:
        if item is not None and item not in seen:
            seen.add(item)
            result.append(item)
    return result


def _find_library(lib, libdirs, os_name):
    patterns = _LIB_PATTERNS.get(os_name, _LIB_PATTERNS["_default"])
    for libdir in libdirs:
        for pattern in patterns:
            candidate = os.path.join(libdir, pattern.format(name=lib))
            if os.path.isfile(candidate):
                return candidate
    return None


def _cmake_path(absolute, package_folder, payload):
    rel = os.path.relpath(absolute, package_folder).replace(os.sep, "/")
    if rel.startswith(".."):
        return None
    rel = "" if rel == "." else "/" + rel
    return "${CMAKE_CURRENT_LIST_DIR}/" + payload + rel


def _version_variables(target, version):
    parts = str(version).split(".")
    while len(parts) < 3:
        parts.append("0")
    major, minor, patch = parts[0], parts[1], parts[2]
    return "\n".join([
        f'set({target}_VERSION_STRING "{version}")',
        f'set({target}_VERSION "{version}")',
        f'set({target}_VERSION_MAJOR "{major}")',
        f'set({target}_VERSION_MINOR "{minor}")',
        f'set({target}_VERSION_PATCH "{patch}")',
        f'set({target}_MAJOR_VERSION "{major}")',
        f'set({target}_MINOR_VERSION "{minor}")',
        f'set({target}_PATCH_VERSION "{patch}")',
    ])


def _engine_target(name, cpp_info):
    return str(cpp_info.get_property("cmake_file_name") or name)


def _engine_aliases(cpp_info, target):
    aliases = []
    primary = cpp_info.get_property("cmake_target_name")
    if primary:
        aliases.append(str(primary))
    aliases.extend(cpp_info.get_property("cmake_target_aliases") or [])
    return [alias for alias in _unique(aliases) if alias != f"3rdParty::{target}"]


def _dependencies(node, packaged_names):
    dependencies = []
    for dependency in node.conanfile.dependencies.host.values():
        if dependency.ref is None:
            continue
        name = str(dependency.ref.name)
        if name not in packaged_names or name == str(node.ref.name):
            continue
        dependencies.append((name, _engine_target(name, dependency.cpp_info)))
    return _unique(dependencies)


def _dependency_prelude(dependencies):
    if not dependencies:
        return ""
    lines = [
        "# Resolve separately packaged Conan dependencies when loaded by O3DE.",
        "if (COMMAND ly_download_associated_package)",
    ]
    for _name, target in dependencies:
        lines += [
            f"    ly_download_associated_package({target})",
            f"    find_package({target} REQUIRED MODULE)",
        ]
    lines += ["endif()", ""]
    return "\n".join(lines)


def _dependency_links(dependencies, target, indent="    "):
    lines = []
    for _name, dependency_target in dependencies:
        lines += [
            f"{indent}if (TARGET 3rdParty::{dependency_target})",
            f"{indent}    set_property(TARGET 3rdParty::{target} APPEND PROPERTY "
            f"INTERFACE_LINK_LIBRARIES 3rdParty::{dependency_target})",
            f"{indent}endif()",
        ]
    return lines


def _collect_usage(node, payload, os_name):
    cpp_info = node.conanfile.cpp_info.aggregated_components()
    package_folder = node.conanfile.package_folder

    includedirs = [_cmake_path(path, package_folder, payload)
                   for path in cpp_info.includedirs or []]
    resolved, missing = [], []
    for lib in cpp_info.libs or []:
        found = _find_library(lib, cpp_info.libdirs or [], os_name)
        if found:
            resolved.append(_cmake_path(found, package_folder, payload))
        else:
            missing.append(lib)

    return {
        "includedirs": _unique(includedirs),
        "libraries": _unique(resolved),
        "missing": _unique(missing),
        "system_libs": _unique(cpp_info.system_libs or []),
        "frameworks": _unique(cpp_info.frameworks or []),
        "defines": _unique(cpp_info.defines or []),
    }


def _generate_config(name, version, target, usage, aliases, dependencies):
    body = [_HEADER, _dependency_prelude(dependencies)]
    if usage["missing"]:
        body.append("# Unresolved libraries reported by the recipe: "
                    + ", ".join(usage["missing"]) + "\n")

    includedirs = usage["includedirs"]
    resolved = usage["libraries"]
    lines = [
        f"if (NOT TARGET 3rdParty::{target})",
        f'    set(_target "3rdParty::{target}")',
    ]
    if includedirs:
        joined = " ".join(f'"{path}"' for path in includedirs)
        lines += [
            f"    set({target}_INCLUDE_DIRS {joined})",
            f"    set({target}_INCLUDE_DIR ${{{target}_INCLUDE_DIRS}})",
        ]
    if resolved:
        joined = " ".join(f'"{path}"' for path in resolved)
        lines += [
            f"    set({target}_LIBRARIES {joined})",
            f"    set({target}_LIBRARY ${{{target}_LIBRARIES}})",
        ]

    lines += [
        "    " + _version_variables(target, version).replace("\n", "\n    "),
        f"    set({target}_FOUND True)",
        "",
        f"    add_library(${{_target}} {'STATIC' if resolved else 'INTERFACE'} IMPORTED GLOBAL)",
    ]
    for alias in aliases:
        lines.append(f"    add_library({alias} ALIAS ${{_target}})")
    if resolved:
        lines.append(f'    set_target_properties(${{_target}} PROPERTIES IMPORTED_LOCATION "{resolved[0]}")')

    link = list(resolved[1:]) + list(usage["system_libs"])
    link += [f"-framework {framework}" for framework in usage["frameworks"]]
    if link:
        joined = ";".join(link)
        lines.append(f'    set_target_properties(${{_target}} PROPERTIES INTERFACE_LINK_LIBRARIES "{joined}")')
    lines += _dependency_links(dependencies, target)

    if usage["defines"]:
        joined = ";".join(usage["defines"])
        lines.append(f'    set_target_properties(${{_target}} PROPERTIES INTERFACE_COMPILE_DEFINITIONS "{joined}")')
    if includedirs:
        lines += [
            "",
            "    if (COMMAND ly_target_include_system_directories)",
            f"        ly_target_include_system_directories(TARGET ${{_target}} INTERFACE ${{{target}_INCLUDE_DIRS}})",
            "    else()",
            f"        target_include_directories(${{_target}} SYSTEM INTERFACE ${{{target}_INCLUDE_DIRS}})",
            "    endif()",
        ]
    lines += [
        "",
        "    if (NOT LY_VERSION_ENGINE_NAME)",
        f'        message(STATUS "Using the O3DE version of {target} from ${{CMAKE_CURRENT_LIST_DIR}}")',
        "    endif()",
        "endif()",
        "",
    ]
    body.append("\n".join(lines))
    return "\n".join(body)


def _generate_find_shim(name, target, dependencies, curated):
    lines = [
        _HEADER,
        f"# Backwards compatible entry point for find_package({target} MODULE).",
        _dependency_prelude(dependencies),
        f'include("${{CMAKE_CURRENT_LIST_DIR}}/{name}-config.cmake")',
    ]
    if curated:
        lines += [
            f"if (TARGET 3rdParty::{target})",
            *_dependency_links(dependencies, target),
            "endif()",
        ]
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------------------
# staging
# --------------------------------------------------------------------------------------

def _copy_payload(source, destination):
    def ignore(directory, names):
        if os.path.abspath(directory) == os.path.abspath(source):
            return set(EXCLUDED_FROM_PAYLOAD) & set(names)
        return set()

    shutil.copytree(source, destination, symlinks=True, ignore=ignore, dirs_exist_ok=True)


def _license_path(stage, payload):
    prefix = payload + "/"
    licenses = os.path.join(stage, payload, "licenses")
    if os.path.isdir(licenses):
        names = [name for name in sorted(os.listdir(licenses))
                 if os.path.isfile(os.path.join(licenses, name))]
        if names:
            return f"{prefix}licenses/{names[0]}"

    root = os.path.join(stage, payload)
    for name in sorted(os.listdir(root)) if os.path.isdir(root) else []:
        if name.upper().startswith(("LICENSE", "COPYING")):
            return prefix + name
    return None


def _copy_curated_cmake(name, stage):
    source = os.path.join(ROOT, "recipes", name, "all", "cmake")
    if not os.path.isdir(source):
        return set()
    shutil.copytree(source, stage, symlinks=True, dirs_exist_ok=True)
    return set(os.listdir(source))


def _source_url(conanfile):
    def search(value):
        if isinstance(value, dict):
            url = value.get("url")
            if isinstance(url, str):
                return url
            if isinstance(url, (list, tuple)) and url and isinstance(url[0], str):
                return url[0]
            for nested in value.values():
                found = search(nested)
                if found:
                    return found
        elif isinstance(value, (list, tuple)):
            for nested in value:
                found = search(nested)
                if found:
                    return found
        return None

    data = getattr(conanfile, "conan_data", None) or {}
    found = search(data.get("sources"))
    if found:
        return found
    git_url = getattr(conanfile, "_git_url", None)
    return git_url if isinstance(git_url, str) else ""


def _build_package(node, platform, staging_root, output_folder,
                   os_name, packaged_names):
    conanfile = node.conanfile
    name = str(node.ref.name)
    version = str(node.ref.version)
    payload = name

    stage = os.path.join(staging_root, name)
    os.makedirs(stage)
    _copy_payload(conanfile.package_folder, os.path.join(stage, payload))

    curated = _copy_curated_cmake(name, stage)
    target = _engine_target(name, conanfile.cpp_info)
    dependencies = _dependencies(node, packaged_names)
    aliases = _engine_aliases(conanfile.cpp_info, target)

    config_name = f"{name}-config.cmake"
    curated_config = config_name in curated
    if not curated_config:
        usage = _collect_usage(node, payload, os_name)
        _write(os.path.join(stage, config_name),
               _generate_config(name, version, target, usage, aliases, dependencies))

    shim_name = f"Find{target}.cmake"
    if shim_name not in curated:
        _write(os.path.join(stage, shim_name),
               _generate_find_shim(name, target, dependencies, curated_config))

    license_file = _license_path(stage, payload)
    if not license_file:
        raise RuntimeError(f"{name}/{version}: no license file found in its Conan package")

    license_name = conanfile.license
    if isinstance(license_name, (list, tuple)):
        license_name = " AND ".join(str(item) for item in license_name)
    descriptor = {
        "URL": conanfile.homepage or conanfile.url or _source_url(conanfile),
        "License": str(license_name or "custom"),
        "LicenseFile": license_file,
    }

    revision = _deployment_revision(node, stage, descriptor)
    package_name = f"{name}-{version}-{platform}-{revision}"
    descriptor = {"PackageName": package_name, **descriptor}
    descriptor_path = os.path.join(stage, DESCRIPTOR_NAME)
    _write(descriptor_path, json.dumps(descriptor, indent=4) + "\n")

    relpaths = _payload_files(stage)
    manifest = "".join(
        f"{_hash_file(os.path.join(stage, relpath))} *{relpath}\n"
        for relpath in relpaths
    )
    archive_path = os.path.join(output_folder, package_name + ARCHIVE_EXT)
    _archive(stage, relpaths, manifest, archive_path)

    archive_hash = _hash_file(archive_path)
    _write(os.path.join(output_folder, package_name + HASH_EXT),
           f"{archive_hash} *{package_name + ARCHIVE_EXT}\n")
    _write(os.path.join(output_folder, package_name + CONTENT_HASH_EXT), manifest)
    shutil.copyfile(descriptor_path,
                    os.path.join(output_folder, f"{package_name}.{DESCRIPTOR_NAME}"))

    print(f"    {package_name + ARCHIVE_EXT}  {archive_hash}")
    return {
        "package_name": package_name,
        "archive": package_name + ARCHIVE_EXT,
        "sha256": archive_hash,
        "targets": [target],
        "reference": f"{name}/{version}",
        "conan_reference": _package_reference(node),
        "platform": platform,
    }


def _write(path, content):
    with open(path, "w", encoding="utf8") as handle:
        handle.write(content)


def _remove_artifact(output_folder, package_name):
    for suffix in (ARCHIVE_EXT, HASH_EXT, CONTENT_HASH_EXT, "." + DESCRIPTOR_NAME):
        path = os.path.join(output_folder, package_name + suffix)
        if os.path.isfile(path):
            os.remove(path)


# --------------------------------------------------------------------------------------
# Conan deployer entry point
# --------------------------------------------------------------------------------------

def deploy(graph, output_folder, **kwargs):
    nodes = [
        node for node in graph.nodes
        if node is not graph.root
        and node.conanfile.package_folder is not None
        and getattr(node, "context", "host") == "host"
        and getattr(node.conanfile, "upload_policy", None) != "skip"
    ]
    if not nodes:
        print("nothing to package")
        return

    root = graph.root.conanfile
    platform = root.conf.get("user.o3de:platform", default=None, check_type=str)
    if not platform:
        raise RuntimeError("the host profile must define user.o3de:platform")
    os_value = root.settings.get_safe("os") or nodes[0].conanfile.settings.get_safe("os")
    if os_value is None:
        raise RuntimeError("the host profile must define a Conan os setting")
    os_name = str(os_value)

    os.makedirs(output_folder, exist_ok=True)
    staging_root = os.path.join(output_folder, ".stage")
    if os.path.isdir(staging_root):
        shutil.rmtree(staging_root)
    os.makedirs(staging_root)

    packaged_names = {str(node.ref.name) for node in nodes}
    print(f"Building independent engine packages for {platform}")
    produced = []
    try:
        for node in sorted(nodes, key=lambda item: str(item.ref)):
            produced.append(_build_package(
                node, platform, staging_root, output_folder,
                os_name, packaged_names))
    finally:
        shutil.rmtree(staging_root, ignore_errors=True)

    manifest_path = os.path.join(output_folder, "packages-manifest.json")
    by_reference = {}
    if os.path.isfile(manifest_path):
        with open(manifest_path, encoding="utf8") as handle:
            existing = json.load(handle)
        if existing.get("platform") == platform:
            by_reference = {
                entry["reference"]: entry
                for entry in existing.get("packages", [])
                if os.path.isfile(os.path.join(output_folder, entry["package_name"] + ARCHIVE_EXT))
            }

    for entry in produced:
        previous = by_reference.get(entry["reference"])
        if previous and previous["package_name"] != entry["package_name"]:
            _remove_artifact(output_folder, previous["package_name"])
        by_reference[entry["reference"]] = entry

    merged = sorted(by_reference.values(), key=lambda entry: entry["package_name"].lower())
    _write(manifest_path, json.dumps({"platform": platform, "packages": merged}, indent=2) + "\n")
    print(f"{len(produced)} package(s) written to {output_folder}")
