#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#

import os

from conan import ConanFile
from conan.tools.files import copy


class GladConan(ConanFile):
    """Pre-generated glad loaders for the APIs the engine uses.

    glad is a generator, not a library: its output depends on which APIs, versions and
    extensions were selected. The loaders here are the ones the engine was built and
    tested against, so they are vendored rather than regenerated, which would silently
    change the exported symbol set.

    Header only, in glad's single header mode.
    """

    name = "glad"
    version = "2.0.0-beta"
    description = "Multi-language GL/GLES/EGL/GLX/WGL loader generated by glad"
    homepage = "https://github.com/Dav1dde/glad"
    license = "MIT"
    package_type = "header-library"
    no_copy_source = True

    exports_sources = "include/*", "LICENSE"

    def package(self):
        copy(self, "*.h", os.path.join(self.export_sources_folder, "include"),
             os.path.join(self.package_folder, "include"))
        copy(self, "LICENSE", self.export_sources_folder,
             os.path.join(self.package_folder, "licenses"))

    def package_info(self):
        self.cpp_info.bindirs = []
        self.cpp_info.libdirs = []

    def package_id(self):
        self.info.clear()
